apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nest-js-demo.fullname" . }}-secret
  labels:
    {{- include "nest-js-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
