apiVersion: v1
kind: Namespace
metadata:
  name: nest-js-demo-staging
  labels:
    app.kubernetes.io/name: nest-js-demo
    app.kubernetes.io/environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: nest-js-demo-prod
  labels:
    app.kubernetes.io/name: nest-js-demo
    app.kubernetes.io/environment: production
